import{PUBLICATION,publicWorks,publicWorkById}from"./domain.js";
export const works=[
 {workId:"demo-merhamet",title:"Merhametin İzinde",summary:"İnsan ilişkilerinde merhameti anlatan geliştirme amaçlı örnek eser.",format:"Kısa film",values:["Merhamet","Sorumluluk"],language:"Türkçe",eligible:false,publicationState:PUBLICATION.DEMO,demo:true,version:"demo-1",governance:{rights:false,rasterast:false,mudabbirRequired:false},reading:"Bu metin yalnızca .com arayüzünü geliştirmek için hazırlanmış DEMO içeriğidir. Bilimsel yayın, dini kaynak aktarımı veya onaylanmış Zanistarast eseri değildir.",source:"Mira arayüz geliştirme demosu — yayınlanmış eser değildir."},
 {workId:"demo-emanet",title:"Emanet",summary:"Güven ve sorumluluk temasını gösteren geliştirme örneği.",format:"Hikâye",values:["Güven","Sorumluluk"],language:"Türkçe",eligible:false,publicationState:PUBLICATION.DEMO,demo:true,version:"demo-1",governance:{rights:false,rasterast:false,mudabbirRequired:false},reading:"DEMO: Eser sayfası, okuma katmanı ve ilgili içerik yerleşimini sınamak için geçici metin.",source:"Geliştirme fixture'ı — gerçek kaynak/eser değildir."},
 {workId:"demo-sabir",title:"Bir Anlık Sabır",summary:"Sabır ve iradeli seçim üzerine geliştirme örneği.",format:"Animasyon",values:["Sabır","İrade"],language:"Kurmancî / Türkçe",eligible:false,publicationState:PUBLICATION.DEMO,demo:true,version:"demo-1",governance:{rights:false,rasterast:false,mudabbirRequired:false},reading:"DEMO: Çok dilli temsil alanı için geçici arayüz verisi.",source:"Geliştirme fixture'ı — yayın kaydı değildir."},
 {workId:"blocked-proof",title:"Gizli kontrol kaydı",summary:"Fail-closed test kaydı.",format:"Test",values:[],language:"Türkçe",eligible:false,publicationState:PUBLICATION.BLOCKED,demo:false,version:"test-1",governance:{rights:false,rasterast:false,mudabbirRequired:true,mudabbirApproved:false},reading:"",source:""}
];
export const eligibleWorks=()=>publicWorks(works);
export const eligibleWorkById=id=>publicWorkById(works,id);
