const FALLBACK="ku";
const COPY={
 ku:{era:"Serdema Fıtrat û Exlaqê",civilization:"Şaristaniya Newroza Kawa",nav:{menu:"Menu veke",home:"Malper",discover:"Vekeşîn",search:"Lêgerîn",library:"Pirtûkxaneya min",history:"Dîrok",liked:"Hezkirî",watchLater:"Paşê temaşe bike",queue:"Rêz",settings:"Mîheng"},ui:{language:"Ziman",search:"Lêgerîn",format:"Form",value:"Nirx",recent:"Lêgerînên dawî",saved:"Tomarkirî",libraryData:"Daneyên pirtûkxaneyê",clearHistory:"Dîrokê paqij bike",clearLikes:"Hemû hezkirinan rake",clearSaves:"Tomarkiriyan paqij bike",all:"Hemû",clear:"Paqij bike",empty:"Hê tiştek tune ye.",new:"Nû hatine zêdekirin",demo:"Naveroka DEMO",like:"Hez bike",liked:"Hezkirî",save:"Tomar bike",savedState:"Tomarkirî",share:"Parve bike",read:"Bixwîne / Mijarê fam bike",transcript:"Transkript",sourceTrust:"Çavkanî û agahdariya pêbaweriyê",nextMix:"Piştre / Mix",autoplay:"Xweber bilîze",remix:"Mix nû bike",notFound:"Berhem nehat dîtin",noResults:"Encam nehat dîtin.",searchPrompt:"Ji bo lêgerînê peyvek binivîse.",emptyHistory:"Hê dîroka temaşekirinê tune ye.",emptyLiked:"Hê berhema hezkirî tune ye.",emptySaved:"Hê berhema tomarkirî tune ye.",emptyList:"Lîste vala ye.",emptyQueue:"Rêz vala ye.",notPublishable:"Ev berhem di hewza weşanê ya guncaw de tune ye.",fixtureDisclaimer:"Ev fixture îdiaya pejirandina Rasterast, piştrastkirina zanistî an destûra weşanê ya Müdebbir nake."}},
 en:{era:"The Age of Fitrah and Morality",civilization:"Newroza Kawa Civilization",nav:{menu:"Open menu",home:"Home",discover:"Discover",search:"Search",library:"My library",history:"History",liked:"Liked",watchLater:"Watch later",queue:"Queue",settings:"Settings"},ui:{language:"Language",search:"Search",format:"Format",value:"Value",recent:"Recent searches",saved:"Saved",libraryData:"Library data",clearHistory:"Clear history",clearLikes:"Remove all likes",clearSaves:"Clear saved items",all:"All",clear:"Clear",empty:"Nothing here yet.",new:"New additions",demo:"DEMO content",like:"Like",liked:"Liked",save:"Save",savedState:"Saved",share:"Share",read:"Read / Understand the topic",transcript:"Transcript",sourceTrust:"Source and trust information",nextMix:"Up next / Mix",autoplay:"Autoplay",remix:"Refresh mix",notFound:"Work not found",noResults:"No results found.",searchPrompt:"Type a word to search.",emptyHistory:"No watch history yet.",emptyLiked:"No liked works yet.",emptySaved:"No saved works yet.",emptyList:"The list is empty.",emptyQueue:"The queue is empty.",notPublishable:"This work is not in the publishable pool.",fixtureDisclaimer:"This fixture does not claim Rasterast acceptance, scientific verification, or Müdebbir publication approval."}},
 de:{era:"Zeitalter von Fitrah und Moral",civilization:"Newroza-Kawa-Zivilisation",nav:{menu:"Menü öffnen",home:"Start",discover:"Entdecken",search:"Suchen",library:"Meine Bibliothek",history:"Verlauf",liked:"Gefällt mir",watchLater:"Später ansehen",queue:"Warteschlange",settings:"Einstellungen"},ui:{language:"Sprache",search:"Suchen",format:"Format",value:"Wert",recent:"Letzte Suchen",saved:"Gespeichert",libraryData:"Bibliotheksdaten",clearHistory:"Verlauf löschen",clearLikes:"Alle Likes entfernen",clearSaves:"Gespeicherte löschen",all:"Alle",clear:"Löschen",empty:"Noch nichts vorhanden.",new:"Neu hinzugefügt",demo:"DEMO-Inhalt",like:"Gefällt mir",liked:"Gefällt mir",save:"Speichern",savedState:"Gespeichert",share:"Teilen",read:"Lesen / Thema verstehen",transcript:"Transkript",sourceTrust:"Quellen- und Vertrauensinformationen",nextMix:"Als Nächstes / Mix",autoplay:"Automatisch abspielen",remix:"Mix erneuern",notFound:"Werk nicht gefunden",noResults:"Keine Ergebnisse gefunden.",searchPrompt:"Geben Sie ein Wort für die Suche ein.",emptyHistory:"Noch kein Wiedergabeverlauf.",emptyLiked:"Noch keine favorisierten Werke.",emptySaved:"Noch keine gespeicherten Werke.",emptyList:"Die Liste ist leer.",emptyQueue:"Die Warteschlange ist leer.",notPublishable:"Dieses Werk befindet sich nicht im freigegebenen Veröffentlichungspool.",fixtureDisclaimer:"Dieses Fixture beansprucht weder Rasterast-Akzeptanz noch wissenschaftliche Verifizierung oder eine Veröffentlichungsfreigabe durch Müdebbir."}},
 tr:{era:"Fıtrat ve Ahlak Çağı",civilization:"Newroza Kawa Uygarlığı",nav:{menu:"Menüyü aç",home:"Ana Sayfa",discover:"Keşfet",search:"Ara",library:"Kitaplığım",history:"Geçmiş",liked:"Beğenilenler",watchLater:"Daha Sonra İzle",queue:"Kuyruk",settings:"Ayarlar"},ui:{language:"Dil",search:"Ara",format:"Biçim",value:"Değer",recent:"Son aramalar",saved:"Kaydedilenler",libraryData:"Kitaplık verileri",clearHistory:"Geçmişi temizle",clearLikes:"Tüm beğenileri kaldır",clearSaves:"Kaydedilenleri temizle",all:"Tümü",clear:"Temizle",empty:"Henüz içerik yok.",new:"Yeni Eklenenler",demo:"DEMO içerik",like:"Beğen",liked:"Beğenildi",save:"Kaydet",savedState:"Kaydedildi",share:"Paylaş",read:"Oku / Konuyu Anla",transcript:"Transkript",sourceTrust:"Kaynak ve güven bilgisi",nextMix:"Sıradaki / Mix",autoplay:"Otomatik oynat",remix:"Mix’i yenile",notFound:"Eser bulunamadı",noResults:"Sonuç bulunamadı.",searchPrompt:"Aramak için bir kelime yazın.",emptyHistory:"Henüz izleme geçmişi yok.",emptyLiked:"Henüz beğenilen eser yok.",emptySaved:"Henüz kaydedilen eser yok.",emptyList:"Liste boş.",emptyQueue:"Kuyruk boş.",notPublishable:"Bu eser yayıma uygun havuzda bulunmuyor.",fixtureDisclaimer:"Bu fixture Rasterast kabulü, bilimsel doğrulama veya Müdebbir yayın onayı iddiası taşımaz."}}
};
const LOCALE_KEY="zanistarast-com:locale:v1";
const base=v=>String(v||"").toLowerCase().split("-")[0];
const localeKey=locale=>COPY[base(locale)]?base(locale):FALLBACK;
export function savedLocale(){try{const k=base(localStorage.getItem(LOCALE_KEY));return COPY[k]?k:null}catch{return null}}
export function setLocale(locale){const k=localeKey(locale);try{localStorage.setItem(LOCALE_KEY,k)}catch{}applyIdentityLocale(k);return k}
export function detectLocale(){const saved=savedLocale();if(saved)return saved;for(const v of navigator.languages||[navigator.language]){const k=base(v);if(COPY[k])return k}return FALLBACK}
export function copyFor(locale=detectLocale()){return COPY[localeKey(locale)]}
export function t(path,locale=detectLocale()){let value=copyFor(locale);for(const key of String(path).split("."))value=value?.[key];return typeof value==="string"?value:path}
export function applyIdentityLocale(locale=detectLocale()){const k=localeKey(locale),copy=COPY[k];document.documentElement.lang=k;const e=document.querySelector("#era-title"),c=document.querySelector("#civilization-title");if(e)e.textContent=copy.era;if(c)c.textContent=copy.civilization;document.querySelectorAll("[data-i18n]").forEach(el=>{const v=t(el.dataset.i18n,k);if(v!==el.dataset.i18n)el.textContent=v});document.querySelectorAll("[data-i18n-aria]").forEach(el=>{const v=t(el.dataset.i18nAria,k);if(v!==el.dataset.i18nAria)el.setAttribute("aria-label",v)});document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>{const v=t(el.dataset.i18nPlaceholder,k);if(v!==el.dataset.i18nPlaceholder)el.setAttribute("placeholder",v)});return k}
export{FALLBACK,COPY};
