import assert from "node:assert/strict";
import fs from "node:fs";
import{PUBLICATION,isPubliclyRenderable}from"./domain.js";
import{works,eligibleWorks,eligibleWorkById}from"./data.js";
import{GOVERNANCE,publicGovernance,canRenderPublic}from"./contracts.js";
import{createContentAdapter}from"./content-adapter.js";
import{normalizeRepresentation,hasTraceableMedia,renderMedia}from"./media.js";
import{createUserState,createAccountStateAdapter}from"./user-state.js";
import{createDiscoveryService}from"./discovery.js";
import{publicAdmission as reviewAdmission}from"./review-gates.js";
import{verifyPilotPackage}from"./pilot-verifier.js";
import{runtimeConfig,ENV,PUBLIC_CONFIG_KEYS}from"./runtime-config.js";
import{productionReadiness,containsLikelySecret}from"./production-readiness.js";
import{CAMPAIGN_STATE,CREATIVE_ORIGIN,validateCampaign,validateCreative,exactVersionAdmission,campaignDeliveryState,materialCreativeChange}from"./ad-contracts.js";
import{PROMOTION_KIND,promotionEligible,createPromotionService,promotionPlayback,renderPromotionInterstitial}from"./promotions.js";

const read=p=>fs.readFileSync(new URL(p,import.meta.url),"utf8");
const html=read("./index.html"),css=read("./styles.css"),app=read("./app.js"),data=read("./data.js"),manifest=JSON.parse(read("./manifest.webmanifest")),sw=read("./sw.js");

assert.match(html,/id="main"/);
assert.match(html,/manifest\.webmanifest/);
assert.match(html,/İçeriğe geç/);
assert.match(css,/@media\(max-width:760px\)/);
assert.match(css,/prefers-reduced-motion/);
assert.match(css,/\.media-player/);
assert.match(css,/\.audio-player/);
assert.match(app,/Oku \/ Konuyu Anla/);
assert.match(app,/Kaynak ve güven bilgisi/);
assert.match(app,/contentAdapter\.get\(id\)/);
assert.doesNotMatch(app,/from\"\.\/data\.js\"/);
assert.equal(works.some(w=>w.workId==="blocked-proof"),true);
assert.equal(eligibleWorkById("blocked-proof"),undefined);
assert.equal(eligibleWorks().some(w=>w.workId==="blocked-proof"),false);
assert.ok(eligibleWorks().every(isPubliclyRenderable));
const base={workId:"real-1",title:"Real",summary:"Summary",format:"Film",language:"Türkçe",values:[],demo:false,eligible:true,version:"v1",publicationState:"PUBLISHED"};
assert.equal(publicGovernance({...base,governance:{rights:true,rasterast:true,mudabbirRequired:false}}),GOVERNANCE.ADMITTED);
assert.equal(publicGovernance({...base,governance:{rights:false,rasterast:true,mudabbirRequired:false}}),GOVERNANCE.BLOCKED);
assert.equal(publicGovernance({...base,governance:{rights:true,rasterast:false,mudabbirRequired:false}}),GOVERNANCE.BLOCKED);
assert.equal(publicGovernance({...base,governance:{rights:true,rasterast:true,mudabbirRequired:true,mudabbirApproved:false}}),GOVERNANCE.BLOCKED);
assert.equal(publicGovernance({...base,publicationState:"WITHDRAWN",governance:{rights:true,rasterast:true,mudabbirRequired:false}}),GOVERNANCE.WITHDRAWN);
assert.equal(canRenderPublic({...base,publicationState:"PENDING",governance:{rights:true,rasterast:true,mudabbirRequired:false}}),false);
const gateAdapter=createContentAdapter([{...base,governance:{rights:true,rasterast:true,mudabbirRequired:false},reading:"ok",source:"source"},{...base,workId:"blocked-2",governance:{rights:false,rasterast:true,mudabbirRequired:false}}]);
assert.equal(gateAdapter.list().length,1);
assert.equal(gateAdapter.get("blocked-2"),null);
assert.equal(gateAdapter.get("real-1").sourceSummary,"source");
for(const state of [PUBLICATION.PENDING,PUBLICATION.BLOCKED,PUBLICATION.WITHDRAWN]) assert.equal(isPubliclyRenderable({workId:"x",eligible:true,version:"1",publicationState:state,demo:false}),false);
assert.match(data,/publicationState:PUBLICATION\.DEMO/);
assert.match(data,/demo:true/);
assert.doesNotMatch(data,/eligible:true/);
assert.doesNotMatch(data,/doi\.org|RASTERAST_ACCEPTED|MÜDEBBIR_APPROVED/i);
assert.equal(manifest.display,"standalone");
assert.ok(manifest.start_url);
const rep=normalizeRepresentation({id:"rep-1",version:"v1",kind:"video",src:"/media/a.mp4",mime:"video/mp4",captions:[{src:"/media/tr.vtt",srclang:"tr",label:"Türkçe",default:true}],transcript:"Metin"});
assert.equal(hasTraceableMedia(rep),true);
const rendered=renderMedia(rep);
assert.match(rendered,/<video/);assert.match(rendered,/controls/);assert.match(rendered,/preload="metadata"/);assert.match(rendered,/<track kind="captions"/);assert.match(rendered,/srclang="tr"/);
assert.match(renderMedia({kind:"video",src:"\/x.mp4"}),/sürüm bilgisi doğrulanamadı/);
assert.match(renderMedia({id:"x",version:"1",kind:"unknown",src:"\/x"}),/temsil türü oynatılamıyor/);
assert.match(renderMedia(null),/Medya şu anda kullanılamıyor/);
assert.match(renderMedia(rep,{demo:true}),/DEMO MEDYA ALANI/);assert.deepEqual(normalizeRepresentation({...rep,chapters:[{title:"Başlangıç",start:0}]}).chapters,[{title:"Başlangıç",start:0}]);
const memory=new Map();const storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};const state=createUserState(storage);
assert.equal(state.liked("real-1"),false);assert.equal(state.toggleLike("real-1"),true);assert.equal(state.liked("real-1"),true);assert.deepEqual(state.likedIds(),["real-1"]);
assert.equal(state.toggleSave("real-1"),true);assert.equal(state.saved("real-1"),true);assert.deepEqual(state.savedIds(),["real-1"]);state.visit("real-1");state.visit("real-2");state.visit("real-1");assert.deepEqual(state.history(),["real-1","real-2"]);assert.deepEqual(state.watchLater(),[]);assert.equal(state.watchLaterHas("real-1"),false);assert.equal(state.toggleWatchLater("real-1"),true);assert.equal(state.watchLaterHas("real-1"),true);assert.equal(state.toggleWatchLater("real-1"),false);assert.deepEqual(state.queue(),[]);state.enqueue("real-1");state.enqueue("real-2");state.enqueue("real-1");assert.deepEqual(state.queue(),["real-1","real-2"]);state.moveQueue("real-2",-1);assert.deepEqual(state.queue(),["real-2","real-1"]);state.dequeue("real-2");assert.deepEqual(state.queue(),["real-1"]);assert.equal(state.autoplayNext(),false);assert.equal(state.setAutoplayNext(true),true);assert.equal(state.autoplayNext(),true);
state.setProgress("real-1","v1",{seconds:42});assert.deepEqual(state.progress("real-1","v1"),{seconds:42});assert.equal(state.progress("real-1","v2"),null);
state.clear();assert.equal(state.liked("real-1"),false);assert.equal(state.saved("real-1"),false);
const account=createAccountStateAdapter({load:()=>({ok:true}),save:x=>x});assert.equal(account.available(),true);assert.deepEqual(account.load(),{ok:true});
const discovery=createDiscoveryService(gateAdapter);assert.equal(discovery.search("Real").length,1);assert.equal(discovery.search("blocked").length,0);assert.equal(discovery.related("real-1").some(w=>w.workId==="blocked-2"),false);
const rankedAdapter=createContentAdapter([{...base,workId:"a",title:"A",values:["Adalet"],format:"Film",governance:{rights:true,rasterast:true,mudabbirRequired:false}},{...base,workId:"b",title:"B",values:["Merhamet"],format:"Ses",governance:{rights:true,rasterast:true,mudabbirRequired:false}},{...base,workId:"c",title:"C",values:["Adalet"],format:"Film",governance:{rights:true,rasterast:true,mudabbirRequired:false}}]);const ranked=createDiscoveryService(rankedAdapter);assert.equal(ranked.related("a",{likedIds:["c"]})[0].workId,"c");assert.equal(ranked.related("a",{likedIds:["c"]}).some(w=>w.workId==="blocked-2"),false);
const reviewBase={candidateId:"p",version:"v1",reviews:{similarityRights:{version:"v1",state:"PASS",evidence:["r"]},cultureVisual:{version:"v1",state:"PASS",evidence:["c"]},accessibility:{version:"v1",state:"PASS",evidence:["a"]},rasterast:{version:"v1",state:"PASS",evidence:["x"]},mudabbir:{version:"v1",state:"APPROVED",evidence:["m"]}},unresolvedItems:[]};
assert.equal(reviewAdmission(reviewBase),"ADMITTED");assert.equal(reviewAdmission({...reviewBase,reviews:{...reviewBase.reviews,rasterast:{version:"v2",state:"PASS",evidence:["x"]}}}),"BLOCKED");assert.equal(reviewAdmission({...reviewBase,reviews:{...reviewBase.reviews,similarityRights:{version:"v1",state:"PASS",evidence:[]}}}),"BLOCKED");assert.equal(reviewAdmission({...reviewBase,reviews:{...reviewBase.reviews,mudabbir:{version:"v1",state:"NOT_APPROVED",evidence:["m"]}}}),"BLOCKED");assert.equal(reviewAdmission({...reviewBase,unresolvedItems:[{id:"u",blocking:true}]}),"BLOCKED");
const pilotManifest=JSON.parse(read("./pilots/emanet-irade/candidate-1.json"));const pilotReview=JSON.parse(read("./pilots/emanet-irade/review-state.json"));const pilotUnresolved=JSON.parse(read("./pilots/emanet-irade/unresolved-items.json"));const pilotCheck=verifyPilotPackage(pilotManifest,pilotReview,pilotUnresolved);assert.equal(pilotCheck.valid,true);assert.equal(pilotCheck.admission,"BLOCKED");assert.deepEqual(pilotCheck.errors,[]);
assert.equal(verifyPilotPackage({...pilotManifest,version:"candidate-2"},pilotReview,pilotUnresolved).admission,"BLOCKED");assert.equal(verifyPilotPackage({...pilotManifest,publicAdmission:"ADMITTED"},pilotReview,pilotUnresolved).valid,false);
assert.equal(runtimeConfig({ZANISTARAST_ENV:ENV.LOCAL}).production,false);assert.throws(()=>runtimeConfig({ZANISTARAST_ENV:ENV.PRODUCTION,ZANISTARAST_API_BASE:"http://example.test"}));assert.equal(runtimeConfig({ZANISTARAST_ENV:ENV.PRODUCTION,ZANISTARAST_API_BASE:"https://api.example.test"}).production,true);assert.deepEqual(PUBLIC_CONFIG_KEYS,["ZANISTARAST_ENV","ZANISTARAST_API_BASE"]);
assert.equal(containsLikelySecret("postgresql://user:password@db.example/test"),true);assert.equal(containsLikelySecret("ZANISTARAST_API_BASE=https://api.example.test"),false);
const notReady=productionReadiness({smokeGreen:true});assert.equal(notReady.ready,false);assert.ok(notReady.missing.includes("restoreTested"));assert.equal(productionReadiness({smokeGreen:true,accessibilityChecked:true,performanceChecked:true,secretsScanGreen:true,restoreTested:true,withdrawalTested:true,apiConfigured:true,storageConfigured:true,deploymentApproved:true}).ready,true);
assert.match(sw,/cache:"no-store"/);assert.match(sw,/governed/);assert.match(sw,/shell-v2/);
const readinessState=JSON.parse(read("./readiness-state.json"));assert.equal(readinessState.productionReady,false);assert.equal(readinessState.domainActivationAllowed,false);assert.equal(readinessState.liveClaimAllowed,false);assert.equal(readinessState.packages.F.codeSide,"COMPLETE_AS_BLOCKED_CANDIDATE");assert.equal(readinessState.packages.G.codeSide,"COMPLETE");
assert.match(sw,/caches\.open/);const mediaSource=read("./media.js");assert.match(mediaSource,/next-countdown/);assert.match(mediaSource,/Sıradaki içerik/);assert.match(mediaSource,/data-speed/);assert.match(mediaSource,/requestPictureInPicture/);
const promo={id:"promo-1",version:"p1",kind:PROMOTION_KIND.INTERNAL,state:"ADMITTED",rights:true,rasterast:true,mudabbirRequired:false,targetWorkId:"real-1",targetVersion:"v1"};
assert.equal(promotionEligible(promo,id=>gateAdapter.get(id)),true);
assert.equal(promotionEligible({...promo,targetVersion:"v2"},id=>gateAdapter.get(id)),false);
const promotionService=createPromotionService([promo],{workLookup:id=>gateAdapter.get(id),maxPerSession:1,minWorksBetween:3});
assert.equal(promotionService.next(0)?.id,"promo-1");assert.equal(promotionService.next(4),null);assert.equal(promotionService.remaining(),0);
const playback=promotionPlayback({skipAfterSeconds:5});assert.equal(playback.canSkip(4.9),false);assert.equal(playback.canSkip(5),true);assert.equal(playback.completionAction,"RESUME_REQUESTED_WORK");assert.equal(playback.failureAction,"RESUME_REQUESTED_WORK");
const promoVideoHtml=renderPromotionInterstitial({...promo,representation:{id:"promo-video",version:"pv1",kind:"video",src:"/demo/promo.mp4",mime:"video/mp4"},skipAfterSeconds:5});assert.match(promoVideoHtml,/data-promotion-media/);assert.match(promoVideoHtml,/promo\.mp4/);assert.match(promoVideoHtml,/Atla · 5 sn/);
const unsafePromoVideoHtml=renderPromotionInterstitial({...promo,representation:{kind:"video",src:"/demo/unversioned.mp4"}});assert.doesNotMatch(unsafePromoVideoHtml,/data-promotion-media/);
const campaign={campaignId:"c1",version:"v1",state:CAMPAIGN_STATE.ADMITTED,sponsor:{name:"Sponsor"},startAt:"2026-10-01",endAt:"2026-10-31",claims:[],rightsEvidence:["license"],targetUrl:"https://example.test"};
const creative={creativeId:"cr1",version:"cv1",campaignId:"c1",campaignVersion:"v1",origin:CREATIVE_ORIGIN.MIRA,representation:{id:"r1",version:"cv1"}};
assert.equal(validateCampaign(campaign).valid,true);assert.equal(validateCreative(creative).valid,true);assert.equal(validateCreative({...creative,origin:CREATIVE_ORIGIN.ADVERTISER,trusted:true}).valid,false);
const adReviews=Object.fromEntries(["rights","claims","antiManipulation","culturalMoral","rasterast"].map(k=>[k,{version:"cv1",state:"PASS"}]));
assert.equal(exactVersionAdmission(campaign,creative,adReviews),"ADMITTED");assert.equal(exactVersionAdmission(campaign,{...creative,version:"cv2"},adReviews),"BLOCKED");
assert.equal(campaignDeliveryState(campaign,creative,adReviews,new Date("2026-09-30T12:00:00Z")),"SCHEDULED");
assert.equal(campaignDeliveryState(campaign,creative,adReviews,new Date("2026-10-15T12:00:00Z")),"ACTIVE");
assert.equal(campaignDeliveryState(campaign,creative,adReviews,new Date("2026-11-01T12:00:00Z")),"EXPIRED");
assert.equal(campaignDeliveryState({...campaign,state:CAMPAIGN_STATE.PAUSED},creative,adReviews,new Date("2026-10-15T12:00:00Z")),"BLOCKED");
assert.equal(campaignDeliveryState({...campaign,state:CAMPAIGN_STATE.WITHDRAWN},creative,adReviews,new Date("2026-10-15T12:00:00Z")),"BLOCKED");
assert.equal(materialCreativeChange(creative,{...creative,text:"changed"}),true);assert.equal(materialCreativeChange(creative,{...creative}),false);
console.log("zanistarast-com smoke: OK");