import assert from "node:assert/strict";
import fs from "node:fs";
import{PUBLICATION,isPubliclyRenderable}from"./domain.js";
import{works,eligibleWorks,eligibleWorkById}from"./data.js";
import{GOVERNANCE,publicGovernance,canRenderPublic}from"./contracts.js";
import{createContentAdapter,admitVerifiedCandidate}from"./content-adapter.js";
import{normalizeRepresentation,hasTraceableMedia,renderMedia}from"./media.js";
import{createUserState,createAccountStateAdapter}from"./user-state.js";
import{createDiscoveryService}from"./discovery.js";
import{normalizeTopicMetadata,topicOverlap,topicMatches,topicFacets,topicInterestProfile}from"./topics.js";
import{publicAdmission as reviewAdmission}from"./review-gates.js";
import{verifyPilotPackage}from"./pilot-verifier.js";
import{verifyContentPackage}from"./content-package-verifier.js";
import{validateActivationReceipt}from"./activation-evidence.js";
import{activationStatus}from"./activation-status.js";
import{nextActivationAction,nextActivationActionFromReceipts}from"./activation-handoff.js";
import{runtimeConfig,ENV,PUBLIC_CONFIG_KEYS}from"./runtime-config.js";
import{productionReadiness,offlineReleaseReadiness,containsLikelySecret}from"./production-readiness.js";
import{CAMPAIGN_STATE,CREATIVE_ORIGIN,DELIVERY_SCOPE,PLACEMENT_PURPOSE,validateCampaign,validateCreative,exactVersionAdmission,campaignDeliveryState,materialCreativeChange,renewCampaign,validateDeliveryScope,deliveryScopeMatches}from"./ad-contracts.js";
import{CLAIM_STATUS,createAdSourceLedger,miraCreativeHandoff}from"./ad-source-ledger.js";
import{INSPECTION_STATE,inspectAdCreative,antiManipulationReviewEvidence}from"./ad-inspection.js";
import{AD_PLACEMENT,createAdScheduler,selectPromotionOrInternal}from"./ad-scheduler.js";
import{AUDIT_EVENT,createCampaignAuditLog,lifecycleTransition,shouldDeliverCampaign}from"./ad-lifecycle.js";
import{buildDemoCampaign}from"./ad-demo-campaign.js";
import{advertiserIntake,billingEligibility}from"./ad-external-intake.js";
import{BRIDGE_ORIGIN,bridgeEligible,createBridgeIndex,bridgeNextSteps,externalDiscoveryCandidate,admitExternalCandidate,refreshBridgeRecord,mergeBridgeSearch}from"./discovery-bridge.js";
import{loadOrgDiscovery}from"./bridge-client.js";
import{PROMOTION_KIND,promotionEligible,createPromotionService,promotionPlayback,renderPromotionInterstitial,renderPromotionShelf,PROMOTION_OUTCOME,promotionOutcome}from"./promotions.js";
import{FALLBACK,COPY,INTERFACE_LOCALES,PLANNED_LOCALES,RTL_LOCALES,localeDirection,interfaceLocaleAvailable,localeKey,t}from"./locale.js";
import{createSpeechRouter,speechRecognitionSupport,SPEECH_LOCALES,speechLocale,createSpeechInput}from"./speech-router.js";
import{KURMANCI_VISIBILITY_COUNTRIES,resolveInitialLocale,regionalLanguageContext,kurmanciVisibility}from"./locale-visibility.js";

const read=p=>fs.readFileSync(new URL(p,import.meta.url),"utf8");
const html=read("./index.html"),css=read("./styles.css"),app=read("./app.js"),data=read("./data.js"),manifest=JSON.parse(read("./manifest.webmanifest")),sw=read("./sw.js"),mediaModule=read("./media.js"),userStateModule=read("./user-state.js");

assert.deepEqual(KURMANCI_VISIBILITY_COUNTRIES,["TR","IR","SY","IQ"]);
assert.equal(resolveInitialLocale({savedLocale:"ku",browserLocales:["tr-TR"],country:"TR",availableLocales:["ku","tr"]}),"ku");
assert.equal(resolveInitialLocale({browserLocales:["fa-IR","ku"],country:"IR",availableLocales:["ku","tr"]}),"ku");
assert.equal(resolveInitialLocale({browserLocales:["tr-TR"],country:"TR",availableLocales:["ku","tr"]}),"tr");
assert.deepEqual(kurmanciVisibility({country:"TR",activeLocale:"tr"}),{regional:true,showPersistentKurmanciChoice:true,inferEthnicity:false,forceLocale:false});
assert.equal(kurmanciVisibility({country:"DE",activeLocale:"de"}).regional,false);
assert.deepEqual(regionalLanguageContext({country:"tr"}),{country:"TR",regionalHintAvailable:true,identityInferred:false,languageForced:false});
assert.deepEqual(regionalLanguageContext({country:null}),{country:null,regionalHintAvailable:false,identityInferred:false,languageForced:false});
assert.equal(kurmanciVisibility({country:"TUR",activeLocale:"tr"}).regional,false);
assert.equal(kurmanciVisibility({country:"SY",activeLocale:"ku"}).showPersistentKurmanciChoice,false);
assert.match(html,/data-kurmanci-choice/);
assert.match(app,/runtimeConfig\(\)\.country/);
assert.match(app,/kurmanciVisibility\(\{country:regionalCountry,activeLocale\}\)/);
assert.match(app,/activeLocale=setLocale\("ku"\)/);
assert.match(read("./locale.js"),/resolveInitialLocale/);
assert.equal(runtimeConfig({ZANISTARAST_ENV:"staging",ZANISTARAST_COUNTRY:"tr"}).country,"TR");
assert.equal(runtimeConfig({ZANISTARAST_ENV:"staging"}).country,null);
assert.throws(()=>runtimeConfig({ZANISTARAST_ENV:"staging",ZANISTARAST_COUNTRY:"TUR"}),/ISO alpha-2/);
assert.ok(PUBLIC_CONFIG_KEYS.includes("ZANISTARAST_COUNTRY"));
assert.match(read("./deployment-config.js"),/regional UI visibility only; never identity or language inference/);
assert.equal(FALLBACK,"ku");assert.equal(t("nav.home","ku"),"Malper");assert.equal(t("nav.home","en"),"Home");assert.equal(t("nav.settings","de"),"Einstellungen");assert.equal(t("ui.new","tr"),"Yeni Eklenenler");assert.equal(t("missing.key","ku"),"missing.key");assert.ok(["ku","en","de","tr"].every(k=>COPY[k]?.era&&COPY[k]?.civilization));
assert.match(html,/id="main"/);assert.match(html,/id="speech-search"/);assert.match(html,/data-i18n-aria="ui\.speechSearch"/);assert.match(html,/data-i18n-title="ui\.speechSearch"/);assert.equal(t("ui.speechSearch","ku"),"Bi dengî bigere");assert.equal(t("ui.speechSearch","en"),"Voice search");assert.equal(t("ui.speechSearch","de"),"Sprachsuche");assert.equal(t("ui.speechSearch","tr"),"Sesli ara");assert.match(html,/id="speech-status"/);assert.match(html,/aria-live="polite"/);assert.match(app,/announceSpeech/);assert.match(app,/PERMISSION_DENIED/);assert.match(app,/LOW_CONFIDENCE/);assert.match(app,/NO_SPEECH/);assert.match(app,/NO_MICROPHONE/);assert.match(app,/state==="TRANSCRIPT"/);assert.match(app,/topQ\.value=transcript/);assert.match(app,/createSpeechRouter/);assert.match(app,/createSpeechInput/);const speechModule=read("./speech-router.js");assert.match(speechModule,/terminalState/);assert.match(speechModule,/if\(!terminalState\)onState\("IDLE"\)/);assert.match(speechModule,/if\(active\)return false/);assert.match(speechModule,/if\(!active\)return false/);assert.match(speechModule,/Math\.min\(1,Math\.max\(0/);assert.match(speechModule,/if\(!transcript\)/);assert.equal([...speechModule.matchAll(/recognition\.onstart=/g)].length,1);assert.equal([...speechModule.matchAll(/recognition\.onend=/g)].length,1);assert.match(app,/speechButton\.hidden=!speechInput\.available/);assert.match(app,/speechInput\.stop\(\);speechInput=createSpeechInput/);
assert.match(html,/manifest\.webmanifest/);
assert.match(html,/data-i18n="ui\.skip"/);assert.equal(t("ui.skip","tr"),"İçeriğe geç");assert.equal(t("ui.skip","ku"),"Derbasî naverokê bibe");
assert.match(css,/@media\(max-width:760px\)/);
assert.match(css,/prefers-reduced-motion/);
assert.match(css,/\.media-player/);
assert.match(css,/\.audio-player/);
assert.match(app,/tx\("ui\.read"\)/);
assert.match(app,/discovery\.newest\(4\)/);
assert.match(app,/discovery\.recommended\(\{likedIds:userState\.likedIds\(\),searchInterests:userState\.searchInterests\(\),excludeIds:\[w\.workId,\.\.\.newest\.map\(x=>x\.workId\)\],limit:6\}\)/);
assert.match(app,/data-related-topics/);assert.match(app,/relatedPreview=related\.slice\(0,6\)/);assert.match(app,/tx\("ui\.relatedTopics"\)/);
assert.equal(t("ui.relatedTopics","ku"),"Mijarên têkildar");assert.equal(t("ui.relatedTopics","en"),"Related topics");assert.equal(t("ui.relatedTopics","de"),"Verwandte Themen");assert.equal(t("ui.relatedTopics","tr"),"Benzer konular");
assert.match(app,/data-newest/);
assert.match(app,/data-recommended/);
assert.match(app,/tx\("ui\.newest"\)/);
assert.match(app,/tx\("ui\.recommended"\)/);
assert.match(app,/userState\.toggleLike\(w\.workId\);work\(w\.workId\)/);
assert.match(app,/if\(!w\)\{main\.innerHTML=`<div class="page"><h1>\$\{tx\("ui\.notFound"\)\}<\/h1><p>\$\{tx\("ui\.notPublishable"\)\}<\/p><\/div>`;return\}/);
assert.doesNotMatch(app,/main\.innerHTML='<div class="page"><h1>\$\{tx\("ui\.notFound"\)\}/);
assert.doesNotMatch(app,/toggleLike\(w\.workId\)\?\`♥/);
assert.equal(t("ui.recommended","ku"),"Ji bo te pêşniyar kirin");
assert.equal(t("ui.recommended","en"),"Recommended for you");
assert.equal(t("ui.recommended","de"),"Für dich empfohlen");
assert.equal(t("ui.recommended","tr"),"Sana önerilenler");
assert.equal(t("ui.topic","ku"),"Mijar");assert.equal(t("ui.topic","en"),"Topic");assert.equal(t("ui.topic","de"),"Thema");assert.equal(t("ui.topic","tr"),"Konu");
assert.match(app,/data-filter="topic"/);assert.match(app,/facets\.topics\.map/);assert.match(app,/const baseItems=discovery\.search\(s,opts\),items=topic\?/);
assert.match(app,/tx\("ui\.sourceTrust"\)/);
assert.match(app,/contentAdapter\.get\(id\)/);
assert.doesNotMatch(app,/from\"\.\/data\.js\"/);
assert.equal(works.some(w=>w.workId==="blocked-proof"),true);
assert.equal(eligibleWorkById("blocked-proof"),undefined);
assert.equal(eligibleWorks().some(w=>w.workId==="blocked-proof"),false);
assert.ok(eligibleWorks().every(isPubliclyRenderable));
const base={workId:"real-1",title:"Real",summary:"Summary",format:"Film",language:"Türkçe",values:[],demo:false,eligible:true,version:"v1",publicationState:"PUBLISHED"};
assert.equal(publicGovernance({...base,governance:{rights:true,rasterast:true,mudabbirRequired:false}}),GOVERNANCE.ADMITTED);
assert.equal(publicGovernance({...base,governance:{rights:false,rasterast:true,mudabbirRequired:false}}),GOVERNANCE.BLOCKED);
assert.equal(publicGovernance({...base,governance:{rights:true,rasterast:false,mudabbirRequired:false}}),GOVERNANCE.BLOCKED);
assert.equal(publicGovernance({...base,governance:{rights:true,rasterast:true,mudabbirRequired:true,mudabbirApproved:false}}),GOVERNANCE.BLOCKED);
assert.equal(publicGovernance({...base,publicationState:"WITHDRAWN",governance:{rights:true,rasterast:true,mudabbirRequired:false}}),GOVERNANCE.WITHDRAWN);
assert.equal(canRenderPublic({...base,publicationState:"PENDING",governance:{rights:true,rasterast:true,mudabbirRequired:false}}),false);
const gateAdapter=createContentAdapter([{...base,governance:{rights:true,rasterast:true,mudabbirRequired:false},reading:"ok",source:"source"},{...base,workId:"blocked-2",governance:{rights:false,rasterast:true,mudabbirRequired:false}}]);
assert.equal(gateAdapter.list().length,1);
assert.equal(gateAdapter.get("blocked-2"),null);
assert.equal(gateAdapter.get("real-1").sourceSummary,"source");
for(const state of [PUBLICATION.PENDING,PUBLICATION.BLOCKED,PUBLICATION.WITHDRAWN]) assert.equal(isPubliclyRenderable({workId:"x",eligible:true,version:"1",publicationState:state,demo:false}),false);
assert.match(data,/publicationState:PUBLICATION\.DEMO/);
assert.match(data,/demo:true/);
assert.doesNotMatch(data,/eligible:true/);
assert.doesNotMatch(data,/doi\.org|RASTERAST_ACCEPTED|MÜDEBBIR_APPROVED/i);
assert.equal(manifest.display,"standalone");
assert.ok(manifest.start_url);
const rep=normalizeRepresentation({id:"rep-1",version:"v1",kind:"video",src:"/media/a.mp4",mime:"video/mp4",captions:[{src:"/media/tr.vtt",srclang:"tr",label:"Türkçe",default:true}],transcript:"Metin"});
assert.equal(hasTraceableMedia(rep),true);
const rendered=renderMedia(rep);
assert.match(rendered,/<video/);assert.match(rendered,/controls/);assert.match(rendered,/preload="metadata"/);assert.match(rendered,/<track kind="captions"/);assert.match(rendered,/srclang="tr"/);
assert.match(renderMedia({kind:"video",src:"\/x.mp4"},{locale:"tr"}),/sürüm bilgisi doğrulanamadı/);
assert.match(renderMedia({id:"x",version:"1",kind:"unknown",src:"\/x"},{locale:"tr"}),/temsil türü oynatılamıyor/);
assert.match(renderMedia(null,{locale:"tr"}),/Medya şu anda kullanılamıyor/);
assert.match(renderMedia(rep,{demo:true,locale:"tr"}),/DEMO MEDYA ALANI/);assert.deepEqual(normalizeRepresentation({...rep,chapters:[{title:"Başlangıç",start:0}]}).chapters,[{title:"Başlangıç",start:0}]);
const memory=new Map();const storage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)};const state=createUserState(storage);
assert.equal(state.liked("real-1"),false);assert.equal(state.toggleLike("real-1"),true);assert.equal(state.liked("real-1"),true);assert.deepEqual(state.likedIds(),["real-1"]);
assert.equal(state.toggleSave("real-1"),true);assert.equal(state.saved("real-1"),true);assert.deepEqual(state.savedIds(),["real-1"]);state.visit("real-1");state.visit("real-2");state.visit("real-1");assert.deepEqual(state.history(),["real-1","real-2"]);assert.deepEqual(state.watchLater(),[]);assert.equal(state.watchLaterHas("real-1"),false);assert.equal(state.toggleWatchLater("real-1"),true);assert.equal(state.watchLaterHas("real-1"),true);assert.equal(state.toggleWatchLater("real-1"),false);assert.deepEqual(state.queue(),[]);state.enqueue("real-1");state.enqueue("real-2");state.enqueue("real-1");assert.deepEqual(state.queue(),["real-1","real-2"]);state.moveQueue("real-2",-1);assert.deepEqual(state.queue(),["real-2","real-1"]);state.dequeue("real-2");assert.deepEqual(state.queue(),["real-1"]);assert.equal(state.autoplayNext(),false);assert.equal(state.setAutoplayNext(true),true);assert.equal(state.autoplayNext(),true);
state.setProgress("real-1","v1",{seconds:42});assert.deepEqual(state.progress("real-1","v1"),{seconds:42});assert.equal(state.progress("real-1","v2"),null);
state.clear();assert.equal(state.liked("real-1"),false);assert.equal(state.saved("real-1"),false);
const account=createAccountStateAdapter({load:()=>({ok:true}),save:x=>x});assert.equal(account.available(),true);assert.deepEqual(account.load(),{ok:true});
const discovery=createDiscoveryService(gateAdapter);assert.equal(discovery.search("Real").length,1);
const recommendationAdapter=createContentAdapter([
 {...base,workId:"liked",format:"Film",values:["mercy"],publishedAt:"2026-01-01",governance:{rights:true,rasterast:true,mudabbirRequired:false}},
 {...base,workId:"same-value",format:"Text",values:["mercy"],publishedAt:"2026-01-02",governance:{rights:true,rasterast:true,mudabbirRequired:false}},
 {...base,workId:"same-format",format:"Film",values:["other"],publishedAt:"2026-01-03",governance:{rights:true,rasterast:true,mudabbirRequired:false}},
 {...base,workId:"blocked-rec",format:"Film",values:["mercy"],publishedAt:"2026-01-04",governance:{rights:false,rasterast:true,mudabbirRequired:false}}
]);
const recommendationDiscovery=createDiscoveryService(recommendationAdapter);
assert.deepEqual(recommendationDiscovery.recommended({likedIds:["liked"],excludeIds:["liked"]}).map(w=>w.workId),["same-value","same-format"]);
assert.equal(recommendationDiscovery.recommended({likedIds:["liked"]}).some(w=>w.workId==="blocked-rec"),false);
assert.equal(recommendationDiscovery.recommended({likedIds:["liked"],limit:1}).length,1);
assert.deepEqual(recommendationDiscovery.recommended({likedIds:["liked"],excludeIds:["liked","same-value"]}).map(w=>w.workId),["same-format"]);
const unrelatedAdapter=createContentAdapter([
 {...base,workId:"liked-only",format:"Film",values:["mercy"],governance:{rights:true,rasterast:true,mudabbirRequired:false}},
 {...base,workId:"unrelated",format:"Audio",values:["justice"],governance:{rights:true,rasterast:true,mudabbirRequired:false}}
]);
const unrelatedDiscovery=createDiscoveryService(unrelatedAdapter);
assert.deepEqual(unrelatedDiscovery.recommended({likedIds:["liked-only"],excludeIds:["liked-only"]}),[]);
assert.equal(unrelatedDiscovery.recommended({excludeIds:["liked-only"]})[0].workId,"unrelated");
assert.deepEqual(recommendationDiscovery.newest().map(w=>w.workId),["same-format","same-value","liked"]);
assert.equal(recommendationDiscovery.newest().some(w=>w.workId==="blocked-rec"),false);
assert.equal(recommendationDiscovery.search("blocked").some(w=>w.workId==="blocked-rec"),false);
assert.equal(recommendationDiscovery.related("liked").some(w=>w.workId==="blocked-rec"),false);
assert.deepEqual(normalizeTopicMetadata({topics:[" Rabûn ","rabûn"],tags:["Tarih"],values:["Mabûn"]}).topics,["rabûn","tarih","mabûn"]);
assert.equal(topicOverlap({topics:["Kuantum","Sosyoloji"]},{tags:["kuantum"]}),1);
assert.equal(topicMatches({topics:["Kuantum Fiziği"]},"kuantum"),true);
assert.equal(topicMatches({topics:["IRAK"]},"irak"),true);
assert.equal(topicMatches({topics:["ÎRO"]},"îro"),true);
assert.doesNotMatch(read("./topics.js"),/toLocaleLowerCase\("tr"\)/);
assert.doesNotMatch(read("./discovery.js"),/toLocaleLowerCase\("tr"\)/);
assert.doesNotMatch(read("./user-state.js"),/toLocaleLowerCase\("tr"\)/);
const topicAdapter=createContentAdapter([
 {...base,workId:"topic-source",title:"Kaynak",summary:"Kaynak",format:"Text",values:[],topics:["Rabûn"],governance:{rights:true,rasterast:true,mudabbirRequired:false}},
 {...base,workId:"topic-match",title:"Eşleşme",summary:"Eşleşme",format:"Audio",values:[],tags:["rabûn"],governance:{rights:true,rasterast:true,mudabbirRequired:false}},
 {...base,workId:"topic-blocked",title:"Rabûn blocked",summary:"Blocked",format:"Audio",values:[],topics:["Rabûn"],governance:{rights:false,rasterast:true,mudabbirRequired:false}}
]);
const topicDiscovery=createDiscoveryService(topicAdapter);
assert.deepEqual(topicDiscovery.search("rabûn").map(w=>w.workId),["topic-source","topic-match"]);
assert.equal(topicDiscovery.search("rabûn").some(w=>w.workId==="topic-blocked"),false);
assert.equal(topicDiscovery.related("topic-source")[0].workId,"topic-match");
const unrelatedTopicAdapter=createContentAdapter([
 {...base,workId:"source-a",title:"A",summary:"A",format:"Film",values:[],topics:["tarih"],governance:{rights:true,rasterast:true,mudabbirRequired:false}},
 {...base,workId:"same-topic",title:"B",summary:"B",format:"Audio",values:[],topics:["tarih"],governance:{rights:true,rasterast:true,mudabbirRequired:false}},
 {...base,workId:"unrelated-topic",title:"C",summary:"C",format:"Text",values:[],topics:["kuantum"],governance:{rights:true,rasterast:true,mudabbirRequired:false}}
]);
assert.deepEqual(createDiscoveryService(unrelatedTopicAdapter).related("source-a").map(w=>w.workId),["same-topic"]);
assert.deepEqual(topicFacets(topicAdapter.list()).map(x=>[x.topic,x.count]),[["rabûn",2]]);
assert.deepEqual(topicDiscovery.facets().topics.map(x=>[x.topic,x.count]),[["rabûn",2]]);
assert.equal(topicDiscovery.facets().topics.some(x=>x.topic.includes("blocked")),false);
assert.deepEqual(topicInterestProfile({" Rabûn ":1,"Kuantum":2,"Sosyoloji":25}),[{topic:"sosyoloji",count:20},{topic:"kuantum",count:2}]);
assert.deepEqual(topicDiscovery.recommended({searchInterests:{"rabûn":1},excludeIds:["topic-source"]}).map(w=>w.workId),["topic-match"]);
assert.deepEqual(topicDiscovery.recommended({searchInterests:{"rabûn":2},excludeIds:["topic-source"]}).map(w=>w.workId),["topic-match"]);
assert.equal(topicDiscovery.recommended({searchInterests:{"rabûn":20}}).some(w=>w.workId==="topic-blocked"),false);
const interestStore={value:"",getItem(){return this.value},setItem(_k,v){this.value=v}};
const interestState=createUserState(interestStore);
assert.equal(interestState.recordSearchInterest(" Rabûn "),1);
assert.equal(interestState.recordSearchInterest("rabûn"),2);
for(let i=0;i<25;i++)interestState.recordSearchInterest("rabûn");
assert.equal(interestState.searchInterests()["rabûn"],20);
assert.equal(interestState.recordSearchInterest("   "),null);
assert.match(app,/userState\.recordSearchInterest\(q\.value\)/);let speechOpened=null;const speechRouter=createSpeechRouter({search:q=>discovery.search(q),open:id=>{speechOpened=id}});assert.equal(speechRouter.route("Real").status,"ROUTED");assert.equal(speechOpened,"real-1");speechOpened=null;assert.equal(speechRouter.route("blocked").status,"NO_MATCH");assert.equal(speechOpened,null);assert.equal(speechRouter.route("   ").status,"EMPTY");assert.equal(speechLocale("ku"),"ku-TR");assert.equal(speechLocale("tr"),"tr-TR");assert.equal(speechLocale("en"),"en-US");assert.equal(speechLocale("de"),"de-DE");assert.equal(speechLocale("ru"),"ru-RU");assert.equal(speechLocale("zh"),"zh-CN");assert.equal(speechLocale("ja"),"ja-JP");assert.equal(speechLocale("ko"),"ko-KR");assert.equal(speechLocale("vi"),"vi-VN");assert.equal(speechLocale("th"),"th-TH");assert.equal(speechLocale("id"),"id-ID");assert.equal(speechLocale("ar"),"ar-SA");assert.equal(speechLocale("fa"),"fa-IR");assert.equal(speechLocale("fr"),"fr-FR");assert.equal(speechLocale("es"),"es-ES");assert.equal(Object.isFrozen(SPEECH_LOCALES),true);assert.equal(speechLocale("xx"),"ku-TR");assert.equal(speechRecognitionSupport({}).supported,false);let recognized=null;class FakeRecognition{start(){this.started=true}stop(){this.stopped=true}}const speechInput=createSpeechInput({router:{route:q=>{recognized=q}},scope:{SpeechRecognition:FakeRecognition},locale:"ku-TR"});assert.equal(speechInput.available,true);assert.equal(speechInput.start(),true);let lowState=null,lowOpened=false;class LowConfidenceRecognition{start(){}stop(){}}const lowInput=createSpeechInput({router:{route:()=>{lowOpened=true;return{status:"ROUTED"}}},scope:{SpeechRecognition:LowConfidenceRecognition},onState:s=>{lowState=s}});lowInput.start();let speechState=null;class ThrowingRecognition{start(){throw new Error("busy")}stop(){}}const guardedSpeech=createSpeechInput({router:{route:()=>({status:"NO_MATCH"})},scope:{SpeechRecognition:ThrowingRecognition},onState:s=>{speechState=s}});assert.equal(guardedSpeech.start(),false);assert.equal(speechState,"ERROR");let permissionState=null;class PermissionRecognition{start(){}stop(){}}const permissionSpeech=createSpeechInput({router:{route:()=>({status:"NO_MATCH"})},scope:{SpeechRecognition:PermissionRecognition},onState:s=>{permissionState=s}});permissionSpeech.start();assert.equal(discovery.search("blocked").length,0);assert.equal(discovery.related("real-1").some(w=>w.workId==="blocked-2"),false);
const rankedAdapter=createContentAdapter([{...base,workId:"a",title:"A",values:["Adalet"],format:"Film",governance:{rights:true,rasterast:true,mudabbirRequired:false}},{...base,workId:"b",title:"B",values:["Merhamet"],format:"Ses",governance:{rights:true,rasterast:true,mudabbirRequired:false}},{...base,workId:"c",title:"C",values:["Adalet"],format:"Film",governance:{rights:true,rasterast:true,mudabbirRequired:false}}]);const ranked=createDiscoveryService(rankedAdapter);assert.equal(ranked.related("a",{likedIds:["c"]})[0].workId,"c");assert.equal(ranked.related("a",{likedIds:["c"]}).some(w=>w.workId==="blocked-2"),false);
const reviewBase={candidateId:"p",version:"v1",reviews:{provenance:{version:"v1",state:"PASS",evidence:["source-ledger"]},rights:{version:"v1",state:"PASS",evidence:["rights-report"]},quality:{version:"v1",state:"PASS",evidence:["quality-report"]},similarityRights:{version:"v1",state:"PASS",evidence:["r"]},cultureVisual:{version:"v1",state:"PASS",evidence:["c"]},accessibility:{version:"v1",state:"PASS",evidence:["a"]},rasterast:{version:"v1",state:"PASS",evidence:["x"]},mudabbir:{version:"v1",state:"APPROVED",evidence:["m"]}},unresolvedItems:[]};
assert.equal(reviewAdmission(reviewBase),"ADMITTED");assert.equal(reviewAdmission({...reviewBase,reviews:{...reviewBase.reviews,provenance:{version:"v1",state:"PENDING",evidence:["source-ledger"]}}}),"BLOCKED");assert.equal(reviewAdmission({...reviewBase,reviews:{...reviewBase.reviews,rights:{version:"v1",state:"PASS",evidence:[]}}}),"BLOCKED");assert.equal(reviewAdmission({...reviewBase,reviews:{...reviewBase.reviews,quality:{version:"v2",state:"PASS",evidence:["quality-report"]}}}),"BLOCKED");assert.equal(reviewAdmission({...reviewBase,reviews:{...reviewBase.reviews,rasterast:{version:"v2",state:"PASS",evidence:["x"]}}}),"BLOCKED");assert.equal(reviewAdmission({...reviewBase,reviews:{...reviewBase.reviews,similarityRights:{version:"v1",state:"PASS",evidence:[]}}}),"BLOCKED");assert.equal(reviewAdmission({...reviewBase,reviews:{...reviewBase.reviews,mudabbir:{version:"v1",state:"NOT_APPROVED",evidence:["m"]}}}),"BLOCKED");assert.equal(reviewAdmission({...reviewBase,unresolvedItems:[{id:"u",blocking:true}]}),"BLOCKED");
const pilotEvidence=JSON.parse(read("./pilots/emanet-irade/evidence-index.json"));assert.equal(pilotEvidence.candidateId,"pilot-emanet-irade");assert.equal(pilotEvidence.version,"candidate-1");assert.equal(pilotEvidence.publicAdmission,"BLOCKED");assert.equal(pilotEvidence.materialChangeRequiresNewVersion,true);assert.deepEqual(pilotEvidence.gates.filter(g=>g.blocker).map(g=>g.blocker),["U1","U2","U3","U4","U5"]);assert.ok(pilotEvidence.gates.every(g=>Array.isArray(g.requiredEvidence)&&g.requiredEvidence.length>0));
const pilotEvidenceFiles=["source-ledger.md","rights-report.md","quality-report.md","similarity-rights-report.md","cultural-review.md","accessibility-plan.md","rasterast-report.md","mudabbir-decision-package.md"];for(const file of pilotEvidenceFiles){const evidence=read("./pilots/emanet-irade/"+file);assert.match(evidence,/candidate-1/i);assert.match(evidence,/PENDING|NOT READY|NOT APPROVED|BLOCKED|INCOMPLETE|UNVERIFIED/i);}
const pilotPublic=JSON.parse(read("./pilots/emanet-irade/public-content.json"));const pilotMedia=JSON.parse(read("./pilots/emanet-irade/media-asset-manifest.json"));assert.equal(pilotPublic.candidateId,pilotMedia.candidateId);assert.equal(pilotPublic.version,pilotMedia.version);assert.equal(pilotPublic.publicAdmission,"BLOCKED");assert.equal(pilotPublic.sourceWork.publicationStatus,"UNVERIFIED");assert.equal(pilotPublic.sourceWork.doi,null);assert.equal(pilotMedia.status,"NO_FINAL_MEDIA");assert.deepEqual(pilotMedia.assets,[]);assert.equal(pilotMedia.requirements.exactVersionBinding,true);assert.equal(pilotMedia.requirements.rightsEvidenceRequired,true);assert.equal(pilotMedia.requirements.accessibilityEvidenceRequired,true);
const pilotRepresentations=JSON.parse(read("./pilots/emanet-irade/representation-contract.json"));assert.equal(pilotRepresentations.candidateId,"pilot-emanet-irade");assert.equal(pilotRepresentations.version,"candidate-1");assert.equal(pilotRepresentations.publicAdmission,"BLOCKED");assert.ok(pilotRepresentations.representations.every(r=>r.final===false));assert.deepEqual(pilotRepresentations.representations.map(r=>r.kind),["public-text","video","audio","image"]);assert.ok(pilotRepresentations.finalMediaRequiredEvidence.includes("rights-report.md"));assert.ok(pilotRepresentations.finalMediaRequiredEvidence.includes("accessibility-plan.md"));
const pilotCopy=JSON.parse(read("./pilots/emanet-irade/public-copy.json"));assert.equal(pilotCopy.candidateId,"pilot-emanet-irade");assert.equal(pilotCopy.version,"candidate-1");assert.equal(pilotCopy.publicAdmission,"BLOCKED");assert.equal(pilotCopy.canonicalLocale,"tr");assert.deepEqual(Object.keys(pilotCopy.locales),["tr","ku","en","de"]);assert.equal(pilotCopy.locales.tr.status,"DRAFT");for(const locale of ["ku","en","de"])assert.equal(pilotCopy.locales[locale].status,"NOT_TRANSLATED");assert.ok(Object.values(pilotCopy.locales).every(x=>Array.isArray(x.sourceTrace)));
const receiptContext={candidateId:"pilot-emanet-irade",version:"candidate-1",checkIds:["U1","U2","U3","U4","U5"]};assert.equal(validateActivationReceipt({candidateId:"pilot-emanet-irade",version:"candidate-1",checkId:"U1",state:"OPEN",evidence:[]},receiptContext).valid,true);assert.equal(validateActivationReceipt({candidateId:"pilot-emanet-irade",version:"candidate-1",checkId:"U1",state:"RESOLVED",evidence:[]},receiptContext).valid,false);assert.equal(validateActivationReceipt({candidateId:"pilot-emanet-irade",version:"candidate-1",checkId:"U1",state:"RESOLVED",evidence:[{id:"e1",kind:"external-review",reference:"review-ref",exactVersion:"candidate-1"}]},receiptContext).valid,true);assert.equal(validateActivationReceipt({candidateId:"pilot-emanet-irade",version:"candidate-1",checkId:"U1",state:"RESOLVED",evidence:[{id:"e1",kind:"external-review",reference:"review-ref",exactVersion:"candidate-2"}]},receiptContext).valid,false);
const activationEvidenceSchema=JSON.parse(read("./pilots/emanet-irade/activation-evidence.schema.json"));assert.equal(activationEvidenceSchema.schemaVersion,1);assert.deepEqual(activationEvidenceSchema.states,["OPEN","RESOLVED"]);assert.equal(activationEvidenceSchema.rules.resolvedRequiresEvidence,true);assert.equal(activationEvidenceSchema.rules.exactVersionRequired,true);assert.equal(activationEvidenceSchema.rules.repositoryPresenceIsNotApproval,true);assert.equal(activationEvidenceSchema.rules.externalEvidenceMustNotBeSynthesized,true);
const activationChecklist=JSON.parse(read("./pilots/emanet-irade/activation-checklist.json"));assert.equal(activationChecklist.candidateId,"pilot-emanet-irade");assert.equal(activationChecklist.version,"candidate-1");assert.equal(activationChecklist.status,"BLOCKED");assert.equal(activationChecklist.automaticPromotion,false);assert.deepEqual(activationChecklist.checks.map(x=>x.id),["U1","U2","U3","U4","U5"]);assert.ok(activationChecklist.checks.every(x=>x.state==="OPEN"&&x.requires.length>0));
const activationHandoff=JSON.parse(read("./pilots/emanet-irade/activation-handoff.json"));assert.equal(activationHandoff.candidateId,"pilot-emanet-irade");assert.equal(activationHandoff.version,"candidate-1");assert.equal(activationHandoff.status,"WAITING_FOR_EXTERNAL_EVIDENCE");assert.deepEqual(activationHandoff.nextActions.map(x=>x.checkId),["U1","U2","U3","U4","U5"]);assert.deepEqual(activationHandoff.nextActions.find(x=>x.checkId==="U4").dependsOn,["U1","U2","U3"]);assert.deepEqual(activationHandoff.nextActions.find(x=>x.checkId==="U5").dependsOn,["U1","U2","U3","U4"]);assert.equal(nextActivationAction(activationHandoff,[]).checkId,"U1");assert.equal(nextActivationAction(activationHandoff,["U1"]).checkId,"U2");assert.equal(nextActivationAction(activationHandoff,["U1","U2"]).checkId,"U3");assert.equal(nextActivationAction(activationHandoff,["U1","U2","U3"]).checkId,"U4");assert.equal(nextActivationAction(activationHandoff,["U1","U2","U3","U4"]).checkId,"U5");assert.equal(nextActivationAction(activationHandoff,["U1","U2","U3","U4","U5"]),null);const u1Receipt={candidateId:activationChecklist.candidateId,version:activationChecklist.version,checkId:"U1",state:"RESOLVED",evidence:[{id:"e-U1",kind:"external-review",reference:"ref-U1",exactVersion:activationChecklist.version}]};assert.equal(nextActivationActionFromReceipts(activationHandoff,activationChecklist,[u1Receipt]).checkId,"U2");assert.equal(nextActivationActionFromReceipts(activationHandoff,activationChecklist,[{...u1Receipt,evidence:[]}]).checkId,"U1");assert.equal(nextActivationActionFromReceipts(activationHandoff,activationChecklist,[{...u1Receipt,version:"candidate-2"}]).checkId,"U1");
const emptyActivation=activationStatus(activationChecklist,[]);assert.equal(emptyActivation.ready,false);assert.equal(emptyActivation.status,"BLOCKED");assert.ok(emptyActivation.checks.every(x=>x.state==="OPEN"));const resolvedReceipts=activationChecklist.checks.map(x=>({candidateId:activationChecklist.candidateId,version:activationChecklist.version,checkId:x.id,state:"RESOLVED",evidence:[{id:"e-"+x.id,kind:"external-review",reference:"ref-"+x.id,exactVersion:activationChecklist.version}]}));assert.equal(activationStatus(activationChecklist,resolvedReceipts).ready,true);const wrongVersionReceipts=resolvedReceipts.map((x,i)=>i?x:{...x,evidence:[{...x.evidence[0],exactVersion:"candidate-2"}]});assert.equal(activationStatus(activationChecklist,wrongVersionReceipts).ready,false);const partialReceipts=resolvedReceipts.slice(0,4);assert.equal(activationStatus(activationChecklist,partialReceipts).ready,false);const unknownReceipt={candidateId:activationChecklist.candidateId,version:activationChecklist.version,checkId:"U6",state:"RESOLVED",evidence:[{id:"e-U6",kind:"external-review",reference:"ref-U6",exactVersion:activationChecklist.version}]};assert.equal(activationStatus(activationChecklist,[...resolvedReceipts,unknownReceipt]).ready,true);
const pilotManifest=JSON.parse(read("./pilots/emanet-irade/candidate-1.json"));const pilotReview=JSON.parse(read("./pilots/emanet-irade/review-state.json"));const pilotUnresolved=JSON.parse(read("./pilots/emanet-irade/unresolved-items.json"));const fullPilotCheck=verifyContentPackage({manifest:pilotManifest,reviewState:pilotReview,unresolved:pilotUnresolved,evidenceIndex:pilotEvidence,publicContent:pilotPublic,mediaManifest:pilotMedia,representations:pilotRepresentations,publicCopy:pilotCopy});assert.equal(fullPilotCheck.valid,true);assert.equal(fullPilotCheck.admission,"BLOCKED");assert.equal(verifyContentPackage({manifest:pilotManifest,reviewState:pilotReview,unresolved:pilotUnresolved,evidenceIndex:{...pilotEvidence,version:"candidate-2"},publicContent:pilotPublic,mediaManifest:pilotMedia,representations:pilotRepresentations,publicCopy:pilotCopy}).valid,false);
const admittedReviews=Object.fromEntries(Object.entries(reviewBase.reviews).map(([k,v])=>[k,{...v}]));const admittedState={...reviewBase,reviews:admittedReviews,unresolvedItems:[]};const admittedManifest={...pilotManifest,candidateId:"p",version:"v1",publicAdmission:"ADMITTED"};const admittedCommon={candidateId:"p",version:"v1",publicAdmission:"ADMITTED"};const finalPackage=verifyContentPackage({manifest:admittedManifest,reviewState:admittedState,unresolved:{candidateId:"p",version:"v1",items:[]},evidenceIndex:{candidateId:"p",version:"v1"},publicContent:{...admittedCommon},mediaManifest:{candidateId:"p",version:"v1",status:"FINAL_MEDIA",assets:[{id:"asset-1"}]},representations:{...admittedCommon,representations:[{kind:"public-text",final:true},{kind:"video",final:true}]},publicCopy:{...admittedCommon}});assert.equal(finalPackage.valid,true);assert.equal(finalPackage.admission,"ADMITTED");const missingFinalMedia=verifyContentPackage({manifest:admittedManifest,reviewState:admittedState,unresolved:{candidateId:"p",version:"v1",items:[]},evidenceIndex:{candidateId:"p",version:"v1"},publicContent:{...admittedCommon},mediaManifest:{candidateId:"p",version:"v1",status:"NO_FINAL_MEDIA",assets:[]},representations:{...admittedCommon,representations:[{kind:"public-text",final:true}]},publicCopy:{...admittedCommon}});assert.equal(missingFinalMedia.admission,"BLOCKED");assert.ok(missingFinalMedia.errors.includes("FINAL_MEDIA_REQUIRED"));
assert.equal(admitVerifiedCandidate(base,fullPilotCheck),null);assert.equal(admitVerifiedCandidate({...base,demo:true},{valid:true,admission:"ADMITTED"}),null);assert.equal(admitVerifiedCandidate({...base,eligible:false},{valid:true,admission:"ADMITTED"}),null);assert.equal(admitVerifiedCandidate(base,{valid:false,admission:"ADMITTED"}),null);assert.equal(admitVerifiedCandidate(base,{valid:true,admission:"BLOCKED"}),null);
const pilotCheck=verifyPilotPackage(pilotManifest,pilotReview,pilotUnresolved);assert.equal(pilotCheck.valid,true);assert.equal(pilotCheck.admission,"BLOCKED");assert.deepEqual(pilotCheck.errors,[]);
assert.equal(verifyPilotPackage({...pilotManifest,version:"candidate-2"},pilotReview,pilotUnresolved).admission,"BLOCKED");assert.equal(verifyPilotPackage({...pilotManifest,publicAdmission:"ADMITTED"},pilotReview,pilotUnresolved).valid,false);
assert.equal(runtimeConfig({ZANISTARAST_ENV:ENV.LOCAL}).production,false);assert.throws(()=>runtimeConfig({ZANISTARAST_ENV:ENV.PRODUCTION,ZANISTARAST_API_BASE:"http://example.test"}));assert.equal(runtimeConfig({ZANISTARAST_ENV:ENV.PRODUCTION,ZANISTARAST_API_BASE:"https://api.example.test"}).production,true);assert.deepEqual(PUBLIC_CONFIG_KEYS,["ZANISTARAST_ENV","ZANISTARAST_API_BASE","ZANISTARAST_ORG_DISCOVERY_BASE","ZANISTARAST_COUNTRY"]);assert.equal(runtimeConfig({ZANISTARAST_ORG_DISCOVERY_BASE:"https://zanistarast.org/discovery"}).orgDiscoveryBase,"https://zanistarast.org/discovery");assert.throws(()=>runtimeConfig({ZANISTARAST_ORG_DISCOVERY_BASE:"http://zanistarast.org/discovery"}),/HTTPS/);
assert.equal(containsLikelySecret("postgresql://user:password@db.example/test"),true);assert.equal(containsLikelySecret("ZANISTARAST_API_BASE=https://api.example.test"),false);
const notReady=productionReadiness({smokeGreen:true});assert.equal(notReady.ready,false);assert.ok(notReady.missing.includes("restoreTested"));assert.ok(notReady.missing.includes("staticBoundaryGreen"));const offlineReady=offlineReleaseReadiness({smokeGreen:true,staticBoundaryGreen:true,secretsScanGreen:true,restoreTested:true,withdrawalTested:true});assert.equal(offlineReady.ready,true);assert.equal(productionReadiness({smokeGreen:true,staticBoundaryGreen:true,accessibilityChecked:true,performanceChecked:true,secretsScanGreen:true,restoreTested:true,withdrawalTested:true,apiConfigured:true,storageConfigured:true,deploymentApproved:true}).ready,true);
assert.match(sw,/cache:"no-store"/);assert.match(sw,/governed/);assert.match(sw,/shell-v2/);
const readinessState=JSON.parse(read("./readiness-state.json"));assert.equal(readinessState.productionReady,false);assert.equal(readinessState.domainActivationAllowed,false);assert.equal(readinessState.liveClaimAllowed,false);assert.equal(readinessState.packages.F.codeSide,"COMPLETE_AS_BLOCKED_CANDIDATE");assert.equal(readinessState.packages.G.codeSide,"COMPLETE");assert.equal(readinessState.productionEvidence.contentActivation.status,"EXTERNAL_ACTIVATION_REQUIRED");assert.deepEqual(readinessState.productionEvidence.contentActivation.requiredChecks,["U1","U2","U3","U4","U5"]);
assert.match(sw,/caches\.open/);const mediaSource=read("./media.js");assert.match(mediaSource,/next-countdown/);assert.match(mediaSource,/tx\("ui\.nextIn"/);assert.equal(t("ui.nextIn","tr",{seconds:5}),"Sıradaki içerik 5 sn sonra oynatılacak");assert.equal(t("ui.nextIn","en",{seconds:5}),"Next content will play in 5 sec");assert.match(mediaSource,/data-speed/);assert.match(mediaSource,/requestPictureInPicture/);
const promo={id:"promo-1",version:"p1",kind:PROMOTION_KIND.INTERNAL,state:"ADMITTED",rights:true,rasterast:true,mudabbirRequired:false,targetWorkId:"real-1",targetVersion:"v1"};
assert.equal(promotionEligible(promo,id=>gateAdapter.get(id)),true);
assert.equal(promotionEligible({...promo,targetVersion:"v2"},id=>gateAdapter.get(id)),false);
const promotionService=createPromotionService([promo],{workLookup:id=>gateAdapter.get(id),maxPerSession:1,minWorksBetween:3});
assert.equal(promotionService.next(0)?.id,"promo-1");assert.equal(promotionService.next(4),null);assert.equal(promotionService.remaining(),0);
const shelfHtml=renderPromotionShelf([promo]);assert.match(shelfHtml,/Tanıtımlar/);assert.match(shelfHtml,/TANITIM/);assert.match(shelfHtml,/#\/work\/real-1/);assert.equal(renderPromotionShelf([]),"");
assert.match(app,/renderPromotionShelf\(promotionService\.shelf\(\)\)/);
const playback=promotionPlayback({skipAfterSeconds:5});assert.equal(playback.canSkip(4.9),false);assert.equal(playback.canSkip(5),true);assert.equal(playback.completionAction,"RESUME_REQUESTED_WORK");assert.equal(playback.failureAction,"RESUME_REQUESTED_WORK");
assert.equal(promotionOutcome(PROMOTION_OUTCOME.SKIPPED).resumeRequestedWork,true);assert.equal(promotionOutcome(PROMOTION_OUTCOME.SKIPPED).countsAsCompleted,false);
assert.equal(promotionOutcome(PROMOTION_OUTCOME.COMPLETED).resumeRequestedWork,true);assert.equal(promotionOutcome(PROMOTION_OUTCOME.COMPLETED).countsAsCompleted,true);
assert.equal(promotionOutcome(PROMOTION_OUTCOME.FAILED).resumeRequestedWork,true);assert.equal(promotionOutcome(PROMOTION_OUTCOME.FAILED).countsAsCompleted,false);
assert.equal(promotionOutcome("UNKNOWN").valid,false);
const promoVideoHtml=renderPromotionInterstitial({...promo,representation:{id:"promo-video",version:"pv1",kind:"video",src:"/demo/promo.mp4",mime:"video/mp4"},skipAfterSeconds:5});assert.match(promoVideoHtml,/data-promotion-media/);assert.match(promoVideoHtml,/promo\.mp4/);assert.match(promoVideoHtml,/Atla · 5 sn/);
const unsafePromoVideoHtml=renderPromotionInterstitial({...promo,representation:{kind:"video",src:"/demo/unversioned.mp4"}});assert.doesNotMatch(unsafePromoVideoHtml,/data-promotion-media/);
const campaign={campaignId:"c1",version:"v1",state:CAMPAIGN_STATE.ADMITTED,sponsor:{name:"Sponsor"},startAt:"2026-10-01",endAt:"2026-10-31",claims:[],rightsEvidence:["license"],targetUrl:"https://example.test"};
const creative={creativeId:"cr1",version:"cv1",campaignId:"c1",campaignVersion:"v1",origin:CREATIVE_ORIGIN.MIRA,representation:{id:"r1",version:"cv1"}};
assert.equal(validateCampaign(campaign).valid,true);assert.equal(validateCreative(creative).valid,true);assert.equal(validateCreative({...creative,origin:CREATIVE_ORIGIN.ADVERTISER,trusted:true}).valid,false);
const adReviews=Object.fromEntries(["rights","claims","antiManipulation","culturalMoral","rasterast"].map(k=>[k,{version:"cv1",state:"PASS"}]));
assert.equal(exactVersionAdmission(campaign,creative,adReviews),"ADMITTED");assert.equal(exactVersionAdmission(campaign,{...creative,version:"cv2"},adReviews),"BLOCKED");
assert.equal(campaignDeliveryState(campaign,creative,adReviews,new Date("2026-09-30T12:00:00Z")),"SCHEDULED");
assert.equal(campaignDeliveryState(campaign,creative,adReviews,new Date("2026-10-15T12:00:00Z")),"ACTIVE");
assert.equal(campaignDeliveryState(campaign,creative,adReviews,new Date("2026-11-01T12:00:00Z")),"EXPIRED");
assert.equal(campaignDeliveryState({...campaign,state:CAMPAIGN_STATE.PAUSED},creative,adReviews,new Date("2026-10-15T12:00:00Z")),"BLOCKED");
assert.equal(campaignDeliveryState({...campaign,state:CAMPAIGN_STATE.WITHDRAWN},creative,adReviews,new Date("2026-10-15T12:00:00Z")),"BLOCKED");
assert.equal(materialCreativeChange(creative,{...creative,text:"changed"}),true);assert.equal(materialCreativeChange(creative,{...creative}),false);
const adLedger=createAdSourceLedger({campaignId:"c1",campaignVersion:"v1",sources:[{sourceId:"s1",origin:"ADVERTISER",rightsStatus:"CLEARED",reference:"brief"}],claims:[{claimId:"cl1",text:"Test claim",status:CLAIM_STATUS.SUPPORTED,sourceIds:["s1"]}]});
assert.equal(adLedger.valid,true);assert.equal(miraCreativeHandoff(adLedger,{creativeId:"m1",version:"mv1"}).ready,true);
const openLedger=createAdSourceLedger({campaignId:"c1",campaignVersion:"v1",sources:[{sourceId:"s1",rightsStatus:"UNVERIFIED"}],claims:[{claimId:"cl1",status:CLAIM_STATUS.UNVERIFIED,sourceIds:["s1"]}]});assert.equal(miraCreativeHandoff(openLedger,{creativeId:"m1",version:"mv1"}).ready,false);
const badLedger=createAdSourceLedger({campaignId:"c1",campaignVersion:"v1",sources:[],claims:[{claimId:"cl1",status:CLAIM_STATUS.SUPPORTED,sourceIds:["missing"]}]});assert.equal(badLedger.valid,false);
const renewal=renewCampaign({...campaign,impressionEntitlement:100000},{version:"v2",startAt:"2026-11-01",endAt:"2026-12-01",impressionEntitlement:50000});
assert.equal(renewal.ready,true);assert.equal(renewal.campaign.state,CAMPAIGN_STATE.REVIEW);assert.equal(renewal.campaign.impressionEntitlement,50000);assert.equal(renewal.previousVersion,"v1");assert.equal(renewal.requiresFreshReview,true);assert.equal(renewCampaign(campaign,{version:"v1",startAt:"2026-11-01",endAt:"2026-12-01"}).ready,false);
const inspectCreative={...creative,representation:{id:"r1",version:"cv1",kind:"video"}};
assert.equal(inspectAdCreative(inspectCreative,{framesReviewed:true,audioReviewed:true,metadataReviewed:true}).state,INSPECTION_STATE.PASS);
assert.equal(inspectAdCreative(inspectCreative,{framesReviewed:false,audioReviewed:true,metadataReviewed:true}).state,INSPECTION_STATE.REVIEW);
assert.equal(inspectAdCreative({...inspectCreative,inspectionSignals:["HIDDEN_MESSAGE"]},{framesReviewed:true,audioReviewed:true,metadataReviewed:true}).state,INSPECTION_STATE.BLOCK);
assert.equal(inspectAdCreative({...inspectCreative,inspectionSignals:["SYSTEM_WARNING_IMPERSONATION"]},{framesReviewed:true,audioReviewed:true,metadataReviewed:true}).state,INSPECTION_STATE.BLOCK);
const anti=antiManipulationReviewEvidence(inspectAdCreative(inspectCreative,{framesReviewed:true,audioReviewed:true,metadataReviewed:true}));
assert.equal(anti.ready,true);assert.equal(anti.review.version,"cv1");assert.equal(anti.humanOrGovernedReviewRequired,true);
assert.equal(antiManipulationReviewEvidence(inspectAdCreative(inspectCreative,{})).ready,false);
const schedCampaign={...campaign,impressionEntitlement:10};
const schedCandidate={campaign:schedCampaign,creative,reviews:adReviews};
const scheduler=createAdScheduler();
let verdict=scheduler.eligible({...schedCandidate,placement:AD_PLACEMENT.PRE_ROLL,now:new Date("2026-10-15T12:00:00Z"),session:{consumedWorks:0},metrics:{delivered:0}});
assert.equal(verdict.ok,true);scheduler.record({...schedCandidate,placement:AD_PLACEMENT.PRE_ROLL,now:new Date("2026-10-15T12:00:00Z"),session:{consumedWorks:0}});
assert.equal(scheduler.eligible({...schedCandidate,placement:AD_PLACEMENT.PRE_ROLL,now:new Date("2026-10-15T12:16:00Z"),session:{consumedWorks:2},metrics:{delivered:1}}).reason,"INTERRUPTIVE_SPACING");
verdict=scheduler.eligible({...schedCandidate,placement:AD_PLACEMENT.PRE_ROLL,now:new Date("2026-10-15T12:16:00Z"),session:{consumedWorks:3},metrics:{delivered:1}});assert.equal(verdict.ok,true);
scheduler.record({...schedCandidate,placement:AD_PLACEMENT.PRE_ROLL,now:new Date("2026-10-15T12:16:00Z"),session:{consumedWorks:3}});
assert.equal(scheduler.eligible({...schedCandidate,placement:AD_PLACEMENT.PRE_ROLL,now:new Date("2026-10-15T12:40:00Z"),session:{consumedWorks:7},metrics:{delivered:2}}).reason,"SESSION_CREATIVE_CAP");
const fulfilled=createAdScheduler();assert.equal(fulfilled.eligible({...schedCandidate,placement:AD_PLACEMENT.FEED_SPONSORED_CARD,now:new Date("2026-10-15T12:00:00Z"),metrics:{delivered:10}}).reason,"ENTITLEMENT_FULFILLED");
const paused={...schedCandidate,campaign:{...schedCampaign,state:CAMPAIGN_STATE.PAUSED}};assert.equal(createAdScheduler().eligible({...paused,placement:AD_PLACEMENT.FEED_SPONSORED_CARD,now:new Date("2026-10-15T12:00:00Z")}).reason,"CAMPAIGN_NOT_ACTIVE");
const fallback=selectPromotionOrInternal({scheduler:createAdScheduler(),candidates:[schedCandidate],internalAnnouncements:[{id:"internal-1",eligible:true,admitted:true}],placement:AD_PLACEMENT.PRE_ROLL,now:new Date("2026-10-15T12:00:00Z"),metricsByCampaign:{"c1@v1":{delivered:10}}});assert.equal(fallback.kind,"INTERNAL_ANNOUNCEMENT");assert.equal(fallback.item.id,"internal-1");
assert.equal(selectPromotionOrInternal({scheduler:createAdScheduler(),candidates:[],internalAnnouncements:[],placement:AD_PLACEMENT.PRE_ROLL}).kind,"EMPTY");
const audit=createCampaignAuditLog();audit.append({campaignId:"c1",campaignVersion:"v1",type:AUDIT_EVENT.DELIVERED,at:"2026-10-15T12:00:00Z"});assert.equal(audit.history("c1").length,1);
const withdrawn=lifecycleTransition(schedCampaign,CAMPAIGN_STATE.WITHDRAWN,{at:"2026-10-15T12:05:00Z",reason:"RIGHTS_REVOKED"});assert.equal(withdrawn.state,CAMPAIGN_STATE.WITHDRAWN);assert.equal(shouldDeliverCampaign(withdrawn,new Date("2026-10-15T12:06:00Z")),false);
assert.throws(()=>lifecycleTransition(schedCampaign,CAMPAIGN_STATE.WITHDRAWN,{at:"2026-10-15T12:05:00Z"}),/WITHDRAWAL_REASON_REQUIRED/);
const expired=lifecycleTransition(schedCampaign,CAMPAIGN_STATE.EXPIRED,{at:"2026-11-01T00:00:01Z"});assert.equal(expired.lifecycle.reason,"CAMPAIGN_WINDOW_ENDED");assert.equal(shouldDeliverCampaign(expired,new Date("2026-11-01T00:00:01Z")),false);
assert.equal(shouldDeliverCampaign(schedCampaign,new Date("2026-10-15T12:00:00Z")),true);
const demoCampaign=buildDemoCampaign();assert.equal(demoCampaign.demo,true);assert.equal(demoCampaign.publicDeliveryAllowed,false);assert.equal(demoCampaign.ledger.valid,true);assert.equal(demoCampaign.handoff.ready,true);assert.equal(demoCampaign.inspection.state,"PASS");assert.equal(demoCampaign.antiManipulation.ready,true);assert.equal(demoCampaign.campaign.state,CAMPAIGN_STATE.REVIEW);assert.equal(exactVersionAdmission(demoCampaign.campaign,demoCampaign.creative,{}),"BLOCKED");
const externalIntake=advertiserIntake({campaign:{...campaign,targetUrl:"https://sponsor.example/path"},asset:{assetId:"asset-1",version:"av1",kind:"video"},legalAccepted:true,privacyAccepted:true,deploymentReady:true});assert.equal(externalIntake.readyForReview,true);assert.equal(externalIntake.directPublishAllowed,false);assert.equal(externalIntake.billingAllowed,false);assert.equal(externalIntake.asset.trust,"UNTRUSTED_INPUT");
assert.equal(advertiserIntake({campaign,asset:{assetId:"asset-1",version:"av1"}}).readyForReview,false);
assert.equal(advertiserIntake({campaign:{...campaign,targetUrl:"http://unsafe.example"},asset:{assetId:"asset-1",version:"av1"},legalAccepted:true,privacyAccepted:true,deploymentReady:true}).readyForReview,false);
assert.equal(billingEligibility({intake:externalIntake,admissionState:"BLOCKED",commercialApproval:true}).allowed,false);
assert.equal(billingEligibility({intake:externalIntake,admissionState:"ADMITTED",commercialApproval:false}).allowed,false);
assert.equal(billingEligibility({intake:externalIntake,admissionState:"ADMITTED",commercialApproval:true}).allowed,true);
assert.match(html,/id="top-search"/);assert.match(html,/id="top-q"/);assert.match(app,/location\.hash="#\/search"/);assert.match(app,/discovery\.search\(s,opts\)/);assert.match(app,/orgBridge\?\.search\(s\)/);assert.match(app,/mergeBridgeSearch\(items,bridgeItems\)/);assert.match(app,/ui\.scientificSource/);assert.match(app,/tx\("ui\.noResults"\)/);assert.equal(t("ui.noResults","tr"),"Sonuç bulunamadı.");assert.equal(t("ui.noResults","ku"),"Encam nehat dîtin.");
const searchDiscovery=createDiscoveryService(createContentAdapter(works));const facets=searchDiscovery.facets();assert.equal(Array.isArray(facets.formats),true);assert.equal(Array.isArray(facets.languages),true);assert.equal(Array.isArray(facets.values),true);assert.equal(searchDiscovery.suggest("mer").every(x=>x.workId),true);
const bridgeOrg={id:"org-1",version:"v1",origin:BRIDGE_ORIGIN.ORG,canonicalUrl:"https://zanistarast.org/work/1",title:"Scientific source",type:"article",language:"en",topics:["ethics"],status:"PUBLISHED"};
const bridgeCom={id:"com-1",version:"v1",origin:BRIDGE_ORIGIN.COM,canonicalUrl:"https://zanistarast.com/#/work/com-1",title:"Public explanation",type:"video",language:"ku",topics:["ethics"],status:"ADMITTED",rasterast:"PASS",related:["org-1"]};
const bridgeBlocked={...bridgeCom,id:"com-blocked",status:"BLOCKED"};
assert.equal(bridgeEligible(bridgeOrg),true);assert.equal(bridgeEligible(bridgeCom),true);assert.equal(bridgeEligible(bridgeBlocked),false);
const discovered=externalDiscoveryCandidate({id:"ext-1",version:"seen-1",canonicalUrl:"https://example.org/talk",title:"External talk",type:"interview"});assert.equal(discovered.publiclyIndexed,false);assert.equal(bridgeEligible(discovered),false);assert.ok(discovered.requires.includes("RIGHTS_LICENSE"));
assert.equal(admitExternalCandidate(discovered,{rightsStatus:"UNVERIFIED",sourceTrust:"PASS",rasterast:"PASS",reviewedAt:"2026-09-27T03:00:00Z"}).admitted,false);
const admittedExternal=admitExternalCandidate(discovered,{rightsStatus:"LINK_ONLY",sourceTrust:"PASS",rasterast:"PASS",reviewedAt:"2026-09-27T03:00:00Z"});assert.equal(admittedExternal.admitted,true);assert.equal(bridgeEligible(admittedExternal.record),true);
const revokedExternal=refreshBridgeRecord(admittedExternal.record,{available:true,rightsStatus:"REVOKED",checkedAt:"2026-09-27T04:00:00Z"});assert.equal(revokedExternal.withdrawn,true);assert.equal(bridgeEligible(revokedExternal),false);
const bridge=createBridgeIndex([bridgeOrg,bridgeCom,bridgeBlocked]);assert.equal(bridge.search("ethics").length,2);assert.equal(bridge.search("blocked").length,0);assert.equal(bridge.related("com-1")[0].id,"org-1");const mergedBridge=mergeBridgeSearch([{workId:"local-1",version:"v1",title:"Local",format:"video",language:"ku"}],bridge.search("ethics"));assert.equal(mergedBridge.some(x=>x.source==="ORG"&&x.id==="org-1"),true);assert.equal(mergedBridge.some(x=>x.source==="COM"&&x.id==="com-blocked"),false);assert.equal(new Set(mergedBridge.map(x=>x.source+":"+x.id+":"+x.version)).size,mergedBridge.length);const steps=bridgeNextSteps(bridgeCom,bridge);assert.equal(steps[0].label,"Bilimsel kaynağı oku");assert.equal(steps[0].origin,BRIDGE_ORIGIN.ORG);
const unconfiguredOrg=await loadOrgDiscovery({source:{}});assert.equal(unconfiguredOrg.configured,false);assert.equal(unconfiguredOrg.records.length,0);
const orgCfg={ZANISTARAST_ORG_DISCOVERY_BASE:"https://zanistarast.org/discovery.json"};
const orgLoaded=await loadOrgDiscovery({source:orgCfg,fetchImpl:async()=>({ok:true,json:async()=>({records:[bridgeOrg,bridgeBlocked]})})});assert.equal(orgLoaded.available,true);assert.equal(orgLoaded.records.length,1);assert.equal(orgLoaded.records[0].origin,"ORG");
const orgOffline=await loadOrgDiscovery({source:orgCfg,fetchImpl:async()=>{throw Error("offline")}});assert.equal(orgOffline.available,false);assert.equal(orgOffline.records.length,0);
assert.equal(deliveryScopeMatches({type:DELIVERY_SCOPE.GLOBAL},{country:"TR"}),true);assert.equal(deliveryScopeMatches({type:DELIVERY_SCOPE.COUNTRY,countries:["TR"]},{country:"TR"}),true);assert.equal(deliveryScopeMatches({type:DELIVERY_SCOPE.COUNTRY,countries:["DE"]},{country:"TR"}),false);assert.equal(deliveryScopeMatches({type:DELIVERY_SCOPE.REGION,regions:["kurdistan-demo"]},{region:"kurdistan-demo"}),true);assert.equal(validateDeliveryScope({type:DELIVERY_SCOPE.COUNTRY,countries:[]}).valid,false);assert.equal(PLACEMENT_PURPOSE.PUBLIC_SERVICE,"PUBLIC_SERVICE");assert.equal(PLACEMENT_PURPOSE.ZANISTARAST_UPDATE,"ZANISTARAST_UPDATE");
assert.match(mediaModule,/const host=media\.parentElement,tx=/);assert.match(mediaModule,/className="next-countdown"/);assert.match(mediaModule,/<button type="button">\$\{tx\("ui\.cancel"\)\}<\/button>/);assert.match(mediaModule,/host\?\.append\(box\)/);assert.match(mediaModule,/media\.addEventListener\("ended",ended\)/);assert.match(mediaModule,/cancelNext\(\)/);
assert.match(mediaModule,/const editable=el=>el\?\.isContentEditable/);assert.match(mediaModule,/e\.defaultPrevented\|\|e\.altKey\|\|e\.ctrlKey\|\|e\.metaKey\|\|e\.shiftKey/);assert.match(mediaModule,/editable\(e\.target\)\|\|editable\(document\.activeElement\)/);assert.match(mediaModule,/e\.code==="Space"/);assert.match(mediaModule,/e\.code==="ArrowRight"/);assert.match(mediaModule,/e\.code==="ArrowLeft"/);
assert.match(mediaModule,/captionButton\.disabled=true/);assert.match(mediaModule,/captionButton\.setAttribute\("aria-disabled","true"\)/);assert.match(mediaModule,/pipButton\.hidden=true/);assert.match(mediaModule,/fullButton\.hidden=true/);assert.match(mediaModule,/document\.exitFullscreen\?\.\(\)/);assert.match(mediaModule,/media\.requestPictureInPicture/);
assert.match(userStateModule,/Array\.isArray\(ids\)\?ids:\[\]/);assert.match(userStateModule,/typeof id==="string"&&id\.trim\(\)/);assert.match(userStateModule,/\.map\(id=>id\.trim\(\)\)/);assert.match(userStateModule,/if\(!safe\)return s\.queue/);
assert.match(mediaModule,/const safeChapters=\(Array\.isArray\(chapters\)\?chapters:\[\]\)/);assert.match(mediaModule,/x\.start>=0/);assert.match(mediaModule,/x\.title\.trim\(\)/);assert.match(mediaModule,/\.sort\(\(a,b\)=>a\.start-b\.start\)/);assert.match(mediaModule,/const end=Number\.isFinite\(media\.duration\)\?media\.duration:Infinity/);assert.match(mediaModule,/media\.currentTime=Math\.min\(end,chapter\.start\)/);
const malformedMedia=normalizeRepresentation({id:"m",version:"1",kind:"video",src:"media.mp4",captions:{bad:true},chapters:"bad"});assert.deepEqual(malformedMedia.captions,[]);assert.deepEqual(malformedMedia.chapters,[]);
console.log("zanistarast-com smoke: OK");
