import assert from "node:assert/strict";
import fs from "node:fs";
import{PUBLICATION,isPubliclyRenderable}from"./domain.js";
import{works,eligibleWorks,eligibleWorkById}from"./data.js";
import{GOVERNANCE,publicGovernance,canRenderPublic}from"./contracts.js";
import{createContentAdapter}from"./content-adapter.js";

const read=p=>fs.readFileSync(new URL(p,import.meta.url),"utf8");
const html=read("./index.html"),css=read("./styles.css"),app=read("./app.js"),data=read("./data.js"),manifest=JSON.parse(read("./manifest.webmanifest")),sw=read("./sw.js");

assert.match(html,/id="main"/);
assert.match(html,/manifest\.webmanifest/);
assert.match(html,/İçeriğe geç/);
assert.match(css,/@media\(max-width:760px\)/);
assert.match(css,/prefers-reduced-motion/);
assert.match(app,/Oku \/ Konuyu Anla/);
assert.match(app,/Kaynak ve güven bilgisi/);
assert.match(app,/contentAdapter\.get\(id\)/);
assert.doesNotMatch(app,/from\"\.\/data\.js\"/);
assert.equal(works.some(w=>w.workId==="blocked-proof"),true);
assert.equal(eligibleWorkById("blocked-proof"),undefined);
assert.equal(eligibleWorks().some(w=>w.workId==="blocked-proof"),false);
assert.ok(eligibleWorks().every(isPubliclyRenderable));
const base={workId:"real-1",title:"Real",summary:"Summary",format:"Film",language:"Türkçe",values:[],demo:false,eligible:true,version:"v1",publicationState:"PUBLISHED"};
assert.equal(publicGovernance({...base,governance:{rights:true,rasterast:true,mudabbirRequired:false}}),GOVERNANCE.ADMITTED);
assert.equal(publicGovernance({...base,governance:{rights:false,rasterast:true,mudabbirRequired:false}}),GOVERNANCE.BLOCKED);
assert.equal(publicGovernance({...base,governance:{rights:true,rasterast:false,mudabbirRequired:false}}),GOVERNANCE.BLOCKED);
assert.equal(publicGovernance({...base,governance:{rights:true,rasterast:true,mudabbirRequired:true,mudabbirApproved:false}}),GOVERNANCE.BLOCKED);
assert.equal(publicGovernance({...base,publicationState:"WITHDRAWN",governance:{rights:true,rasterast:true,mudabbirRequired:false}}),GOVERNANCE.WITHDRAWN);
assert.equal(canRenderPublic({...base,publicationState:"PENDING",governance:{rights:true,rasterast:true,mudabbirRequired:false}}),false);
const gateAdapter=createContentAdapter([{...base,governance:{rights:true,rasterast:true,mudabbirRequired:false},reading:"ok",source:"source"},{...base,workId:"blocked-2",governance:{rights:false,rasterast:true,mudabbirRequired:false}}]);
assert.equal(gateAdapter.list().length,1);
assert.equal(gateAdapter.get("blocked-2"),null);
assert.equal(gateAdapter.get("real-1").sourceSummary,"source");
for(const state of [PUBLICATION.PENDING,PUBLICATION.BLOCKED,PUBLICATION.WITHDRAWN]) assert.equal(isPubliclyRenderable({workId:"x",eligible:true,version:"1",publicationState:state,demo:false}),false);
assert.match(data,/publicationState:PUBLICATION\.DEMO/);
assert.match(data,/demo:true/);
assert.doesNotMatch(data,/eligible:true/);
assert.doesNotMatch(data,/doi\.org|RASTERAST_ACCEPTED|MÜDEBBIR_APPROVED/i);
assert.equal(manifest.display,"standalone");
assert.ok(manifest.start_url);
assert.match(sw,/caches\.open/);
console.log("zanistarast-com smoke: OK");