const fs=require("node:fs"),path=require("node:path");
const VERSION=1;
function safeId(id){if(typeof id!=="string"||!id||!/^[a-zA-Z0-9._:-]{1,160}$/.test(id))throw Error("INVALID_ID");return id}
function cloneRecords(records){if(!records||typeof records!=="object"||Array.isArray(records))throw Error("INVALID_BACKUP");const out={};for(const[id,value]of Object.entries(records))out[safeId(id)]=structuredClone(value);return out}
function backupEnvelope(records){return{version:VERSION,records:cloneRecords(records)}}
function validateBackup(backup){if(!backup||typeof backup!=="object"||Array.isArray(backup)||backup.version!==VERSION)throw Error("INVALID_BACKUP");return backupEnvelope(backup.records)}
function memoryAdapter(){const map=new Map();return Object.freeze({kind:"memory",persistent:false,async get(id){return map.get(safeId(id))??null},async put(id,value){map.set(safeId(id),structuredClone(value));return true},async remove(id){return map.delete(safeId(id))},async snapshot(){return Object.fromEntries(map)},async backup(){return backupEnvelope(Object.fromEntries(map))},async restore(backup){const x=validateBackup(backup);map.clear();for(const[id,value]of Object.entries(x.records))map.set(id,value);return true}})}
function fileAdapter(dir){fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,"state-v1.json");const read=()=>{try{const x=JSON.parse(fs.readFileSync(file,"utf8"));return validateBackup(x)}catch(e){if(e&&e.code==="ENOENT")return backupEnvelope({});throw e}};const write=x=>{const safe=validateBackup(x),tmp=file+".tmp";fs.writeFileSync(tmp,JSON.stringify(safe));fs.renameSync(tmp,file)};return Object.freeze({kind:"file",persistent:true,async get(id){return read().records[safeId(id)]??null},async put(id,value){const x=read();x.records[safeId(id)]=structuredClone(value);write(x);return true},async remove(id){const x=read(),ok=Object.hasOwn(x.records,safeId(id));delete x.records[safeId(id)];write(x);return ok},async snapshot(){return read().records},async backup(){return read()},async restore(backup){write(validateBackup(backup));return true}})}
function createStorage(env=process.env){const dir=env.ZANISTARAST_STORAGE_DIR;return dir?fileAdapter(dir):memoryAdapter()}
module.exports={VERSION,createStorage,memoryAdapter,fileAdapter,validateBackup};
